apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  namespace: ecommerce-namespace
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: rbcadaing/apigateway:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: ecommerce-namespace
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8080      # The port that will be exposed externally
      targetPort: 8080  # The port on the apigateway container
  type: LoadBalancer  # Exposes the service externally using the Azure's load balancer



