apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: ecommerce-namespace
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: rbcadaing/ecommerce-mongodb:latest
        command: ["mongodb", "--bind_ip_all"]
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongopw

        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ecommerce-namespace
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ecommerce-namespace
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017      # The port that will be exposed externally
      targetPort: 27017  # The port on the apigateway container
  type: LoadBalancer  # Exposes the service externally using the Azure's load balancer



