apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: ecommerce-namespace
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: rbcadaing/ecommerce-mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ecommerce-namespace
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ecommerce-namespace
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306      # The port that will be exposed externally
      targetPort: 3306  # The port on the apigateway container
  type: LoadBalancer  # Exposes the service externally using the Azure's load balancer

