apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-microservice-deployment
  namespace: ecommerce-namespace
  labels:
    app: orders-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-microservice
  template:
    metadata:
      labels:
        app: orders-microservice
    spec:
      containers:
      - name: orders-microservice
        image: rbcadaing/orders-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__MongoDB
          value: mongodb://root:mongopw@mongodb
        - name: UsersMicroserviceUrl
          value: "http://apigateway:8080"
        - name: ProductsMicroserviceUrl
          value: "http://apigateway:8080"
        - name: OrdersDatabaseName
          value: "OrdersDatabase"
        - name: ConnectionStrings__Redis
          value: "redis:6379"
        - name: RabbitMQ__HostName
          value: "rabbitmq"
        - name: RabbitMQ__UserName
          value: "user"
        - name: RabbitMQ__Password
          value: "password"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__ProductExchange
          value: "product.exchange"

---

apiVersion: v1
kind: Service
metadata:
  name: orders-microservice
  namespace: ecommerce-namespace
spec:
  selector:
    app: orders-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP