apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-microservice-deployment
  namespace: ecommerce-namespace
  labels:
    app: products-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-microservice
  template:
    metadata:
      labels:
        app: products-microservice
    spec:
      containers:
      - name: products-microservice
        image: rbcadaing/products-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__DefaultConnection
          value: "Server=mysql;Port=3306;Database=ecommerceproductsdatabase;Uid=root;Pwd=admin;"
        - name: RabbitMQ__HostName
          value: rabbitmq
        - name: RabbitMQ__UserName
          value: user
        - name: RabbitMQ__Password
          value: password
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__ProductExchange
          value: product.exchange
---
apiVersion: v1
kind: Service
metadata:
  name: products-microservice
  namespace: ecommerce-namespace
spec:
  selector:
    app: products-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: products-microservice-lb
#   namespace: ecommerce-namespace
# spec:
#   selector:
#     app: products-microservice
#   ports:
#     - protocol: TCP
#       port: 8080      # The port that will be exposed externally
#       targetPort: 8080  # The port on the apigateway container
#   type: LoadBalancer  # Exposes the service externally using the Azure's load balancer


