apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice-deployment
  namespace: ecommerce-namespace
  labels:
    app: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
      - name: users-microservice
        image: harshaecommerceregistry.azurecr.io/users-microservice:latest
        ports:
        - containerPort: 9090
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__PostgresConnection
          value: "Host=postgres-container:5432;Database=eCommerceUsers;User Id=postgres;Password=admin;"
        - name: RabbitMQ__HostName
          value: rabbitmq
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__UserName
          value: guest
        - name: RabbitMQ__Password
          value: guest
        - name: RabbitMQ__UsersExchange
          value: users.exchange
---

apiVersion: v1
kind: Service
metadata:
  name: users-microservice
  namespace: ecommerce-namespace
spec:
  selector:
    app: users-microservice
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP

