
resources:
- repo: self

variables:
  - group: docker-hub

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
   
    - script: |
        docker login -u rbcadaing -p $(docker_pw)
        docker compose -f docker-compose.build.yaml build apigateway-microservice
        docker compose -f docker-compose.build.yaml push apigateway-microservice
      workingDirectory: '$(Build.SourcesDirectory)'
      displayName: "Build And Push Api Gateway Microservice"

