# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      inputs:
        containerRegistry: 'Personal_Docker_hub'
        command: 'login'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          docker build -t ecommerce-mongodb:latest '$(Build.SourcesDirectory)/deployment/mongodb/Dockerfile'
          
          docker tag ecommerce-mongodb:latest rbcadaing/ecommerce-mongodb:latest
    - task: Docker@2
      displayName: Push to Docker Hub
      inputs:
        containerRegistry: 'Personal_Docker_hub'
        repository: 'rbcadaing/ecommerce-mongodb'
        command: 'push'
