# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Personal_Docker_hub'
        command: 'login'
        
    - script: |
        docker build -t rbcadaing/ecommerce-mongodb:latest .
        docker push rbcadaing/ecommerce-mongodb:latest
      workingDirectory: '$(Build.SourcesDirectory)/deployment/mongodb'
      displayName: "Run script in subfolder"

