# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'rbcadaing/ecommerce-mongodb'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/deployment/mongodb/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push to Docker Hub
      inputs:
        containerRegistry: 'Personal_Docker_hub'
        repository: 'rbcadaing/ecommerce-mongodb'
        command: 'push'
