services:
  mongodb-container:
   image: rbcadaing/ecommerce-mongodb:latest
   build: 
     context: ./deployment/mongodb
     dockerfile: /Dockerfile
   ports:
    - "27017:27017"
   networks:
    - orders-mongodb-network

  mysql-container:
   image: rbcadaing/ecommerce-mysql:latest
   build: 
     context: ./deployment/mysql
     dockerfile: /Dockerfile
   environment:
    - MYSQL_ROOT_PASSWORD=mysqlpw
   ports:
    - "3306:3306"
   networks:
    - products-mysql-network

  postgres-container:
   image: rbcadaing/ecommerce-postgres:latest
   build: 
     context: ./deployment/postgres
     dockerfile: /Dockerfile
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=eCommerceUsers
   ports:
    - "5432:5432"
   networks:
    - users-postgres-network

  redis:
   image: redis:latest
   ports:
    - "6379:6379"
   networks:
    - ecommerce-network

  rabbitmq:
    image: rabbitmq:4.1.2-management
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
    networks:
     - ecommerce-network

  apigateway:
    image: rbcadaing/apigateway:latest
    build:
      context: .
      dockerfile: eCommerceSolution.OrdersMicroservice/ApiGateway/Dockerfile
    ports:
     - "5000:8080"
    networks:
     - ecommerce-network
    depends_on:
     - orders-microservice
     - products-microservice
     - users-microservice

  users-microservice:
   image: rbcadaing/users-microservice:latest
   build: 
    context: .
    dockerfile: eCommerceSolution.UserService/eCommerce.API/Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__PostgresConnection=Host=postgres-container:5432;Database=eCommerceUsers;User Id=postgres;Password=postgrespw;
    - RabbitMQ_HostName=rabbitmq
    - RabbitMQ_Port=5672
    - RabbitMQ_UserName=guest
    - RabbitMQ_Password=guest
    - RabbitMQ_Users_Exchange=users.exchange
   networks:
    - users-postgres-network
    - ecommerce-network
   depends_on: 
    - postgres-container

  products-microservice:
   image: rbcadaing/products-microservice:latest
   build: 
    context: .
    dockerfile: eCommerceSolution.ProductsService/ProductsMicroService.API/Dockerfile
   environment:
   - ConnectionStrings__DefaultConnection=Server=mysql-container;Port=3306;Database=ecommerceproductsdatabase;Uid=root;Pwd=mysqlpw;
   - RabbitMQ__HostName=rabbitmq-container
   - RabbitMQ__UserName=user
   - RabbitMQ__Password=password
   - RabbitMQ_Port=5672
   - RabbitMQ_Product_Exchange=product.exchange
   networks:
    - products-mysql-network
    - ecommerce-network
   depends_on: 
    - mysql-container

  orders-microservice:
    image: rbcadaing/orders-microservice:latest
    build: 
     context: .
     dockerfile: eCommerceSolution.OrdersMicroservice/OrdersMicroservice.API/Dockerfile
    environment:
     - ConnectionStrings__MongoDB=mongodb://root:mongopw@mongodb-container
     - UsersMicroserviceUrl=http://users-microservice:9090
     - ProductsMicroserviceUrl=http://products-microservice:8080
     - OrdersDatabaseName=OrdersDatabase
     - ConnectionStrings__Redis=redis-container:6379
     - RabbitMQ__HostName=rabbitmq-container
     - RabbitMQ__UserName=user
     - RabbitMQ__Password=password
     - RabbitMQ_Port=5672
     - RabbitMQ_Product_Exchange=product.exchange
    networks:
     - orders-mongodb-network
     - ecommerce-network
    depends_on: 
     - mongodb-container
     - rabbitmq
     - redis


networks:
 ecommerce-network:
  driver: bridge
 users-postgres-network:
  driver: bridge
 products-mysql-network:
  driver: bridge
 orders-mongodb-network:
  driver: bridge
