services:
  mongodb-container:
   image: rbcadaing/ecommerce-mongodb:latest
   build: 
     context: ./deployment/mongodb
     dockerfile: /Dockerfile
   environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=mongopw
   ports:
    - "27017:27017"
   networks:
    - ecommerce-network

  mysql-container:
   image: rbcadaing/ecommerce-mysql:latest
   build: 
     context: ./deployment/mysql
     dockerfile: /Dockerfile
   environment:
    - MYSQL_ROOT_PASSWORD=mysqlpw
   ports:
    - "3306:3306"
   networks:
    - ecommerce-network

  postgres-container:
   image: rbcadaing/ecommerce-postgres:latest
   build: 
     context: ./deployment/postgres
     dockerfile: /Dockerfile
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=eCommerceUsers
   ports:
    - "5432:5432"
   networks:
    - ecommerce-network

  redis:
   image: redis:latest
   ports:
    - "6379:6379"
   networks:
    - ecommerce-network

  rabbitmq:
    image: rabbitmq:4.1.2-management
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
    networks:
     - ecommerce-network

  apigateway-microservice:
    image: rbcadaing/apigateway:latest
    build:
      context: .
      dockerfile: eCommerceSolution.GatewayMicroservice/ApiGateway/Dockerfile
    ports:
     - "5000:8080"
    networks:
     - ecommerce-network
    depends_on:
     - orders-microservice
     - products-microservice
     - users-microservice

  users-microservice:
   image: rbcadaing/users-microservice:latest
   build: 
    context: .
    dockerfile: eCommerceSolution.UserService/eCommerce.API/Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__PostgresConnection=Host=postgres-container:5432;Database=eCommerceUsers;User Id=postgres;Password=admin;
    - RabbitMQ__HostName=rabbitmq
    - RabbitMQ__Port=5672
    - RabbitMQ__UserName=guest
    - RabbitMQ__Password=guest
    - RabbitMQ__UsersExchange=users.exchange
   ports:
    - "9090:9090"
   networks:
    - ecommerce-network
   depends_on: 
    - postgres-container

  products-microservice:
   image: rbcadaing/products-microservice:latest
   build: 
    context: .
    dockerfile: eCommerceSolution.ProductsService/ProductsMicroService.API/Dockerfile
   environment:
    - ConnectionStrings__DefaultConnection=Server=mysql-container;Port=3306;Database=ecommerceproductsdatabase;Uid=root;Pwd=mysqlpw;
    - RabbitMQ__HostName=rabbitmq
    - RabbitMQ__UserName=user
    - RabbitMQ__Password=password
    - RabbitMQ__Port=5672
    - RabbitMQ__ProductExchange=product.exchange
   ports:
    - "8080:8080"
   networks:
    - ecommerce-network
   depends_on: 
    - mysql-container

  orders-microservice:
    image: rbcadaing/orders-microservice:latest
    build: 
     context: .
     dockerfile: eCommerceSolution.OrdersMicroservice/OrdersMicroservice.API/Dockerfile
    environment:
     - ConnectionStrings__MongoDB=mongodb://root:mongopw@mongodb-container
     - UsersMicroserviceUrl=http://users-microservice:9090
     - ProductsMicroserviceUrl=http://products-microservice:8080
     - OrdersDatabaseName=OrdersDatabase
     - ConnectionStrings__Redis=redis:6379
     - RabbitMQ__HostName=rabbitmq
     - RabbitMQ__UserName=user
     - RabbitMQ__Password=password
     - RabbitMQ__Port=5672
     - RabbitMQ__ProductExchange=product.exchange
    ports:
     - "9091:8080"
    networks:
     - ecommerce-network
    depends_on: 
     - mongodb-container
     - rabbitmq
     - redis


networks:
 ecommerce-network:
  driver: bridge

