services:
  mongodb-container:
   image: rbcadaing/ecommerce-mongodb:latest
   build: 
     context: .
     dockerfile: mongodb/Dockerfile
   ports:
    - "27017:27017"
   networks:
    - orders-mongodb-network

  mysql-container:
   image: rbcadaing/ecommerce-mysql:latest
   build: 
     context: .
     dockerfile: mysql/Dockerfile
   environment:
    - MYSQL_ROOT_PASSWORD=admin
   ports:
    - "3306:3306"
   networks:
    - products-mysql-network

  postgres-container:
   image: rbcadaing/ecommerce-postgres:latest
   build: 
     context: .
     dockerfile: postgres/Dockerfile
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=eCommerceUsers
   ports:
    - "5432:5432"
   networks:
    - users-postgres-network

  redis:
   image: redis:latest
   ports:
    - "6379:6379"
   networks:
    - ecommerce-network

  rabbitmq:
    image: rabbitmq:4.1.2-management
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
     - ecommerce-network

  apigateway:
    image: rbcadaing/apigateway:latest
    build:
      context: .
      dockerfile: eCommerceSolution/eCommerceSolution.OrdersMicroservice/ApiGateway/Dockerfile
    ports:
     - "5000:8080"
    networks:
     - ecommerce-network
    depends_on:
     - orders-microservice
     - products-microservice
     - users-microservice

  users-microservice:
   image: rbcadaing/users-microservice:latest
   build: 
    context: .
    dockerfile: eCommerceSolution/eCommerceSolution.UserService/eCommerce.API/Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - POSTGRES_HOST=postgres-container
    - POSTGRES_PORT=5432
    - POSTGRES_DATABASE=eCommerceUsers
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin
    - RabbitMQ_HostName=rabbitmq
    - RabbitMQ_Port=5672
    - RabbitMQ_UserName=guest
    - RabbitMQ_Password=guest
    - RabbitMQ_Users_Exchange=users.exchange
   networks:
    - users-postgres-network
    - ecommerce-network
   depends_on: 
    - postgres-container

  products-microservice:
   image: rbcadaing/products-microservice:latest
   build: 
    context: .
    dockerfile: eCommerceSolution/eCommerceSolution.ProductsService/ProductsMicroService.API/Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - MYSQL_HOST=mysql-container
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=ecommerceproductsdatabase
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin
    - RabbitMQ_HostName=rabbitmq
    - RabbitMQ_Port=5672
    - RabbitMQ_UserName=guest
    - RabbitMQ_Password=guest
    - RabbitMQ_Products_Exchange=products.exchange
   networks:
    - products-mysql-network
    - ecommerce-network
   depends_on: 
    - mysql-container

  orders-microservice:
    image: rbcadaing/orders-microservice:latest
    build: 
     context: .
     dockerfile: eCommerceSolution/eCommerceSolution.OrdersMicroService/OrdersMicroservice.API/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - MONGODB_HOST=mongodb-container
     - MONGODB_PORT=27017
     - MONGODB_DATABASE=OrdersDatabase
     - UsersMicroservicePort=8080
     - UsersMicroserviceName=apigateway
     - ProductsMicroservicePort=8080
     - ProductsMicroserviceName=apigateway
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - RabbitMQ_HostName=rabbitmq
     - RabbitMQ_Port=5672
     - RabbitMQ_UserName=guest
     - RabbitMQ_Password=guest
     - RabbitMQ_Products_Exchange=products.exchange
     - RabbitMQ_Users_Exchange=users.exchange
    networks:
     - orders-mongodb-network
     - ecommerce-network
    depends_on: 
     - mongodb-container
     - rabbitmq
     - redis


networks:
 ecommerce-network:
  driver: bridge
 users-postgres-network:
  driver: bridge
 products-mysql-network:
  driver: bridge
 orders-mongodb-network:
  driver: bridge
