
services:
 mysql-container:
  image: rbcadaing/ecommerce-mysql:latest
  build: 
    context: ./deployment/mysql
    dockerfile: /Dockerfile
  environment:
   - MYSQL_ROOT_PASSWORD=mysqlpw
  ports:
   - "3306:3306"
  networks:
   - ecommerce-network
  #hostname: mysql-host-productsmicroservice

 mongodb-container:
  image: rbcadaing/ecommerce-mongodb:latest
  build: 
    context: ./deployment/mongodb
    dockerfile: /Dockerfile
  ports:
   - "27017:27017"
  networks:
   - ecommerce-network

 postgres-container:
  image: rbcadaing/ecommerce-postgres:latest
  build: 
    context: ./deployment/postgres
    dockerfile: /Dockerfile
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=admin
   - POSTGRES_DB=eCommerceUsers
  ports:
   - "5432:5432"
  networks:
   - ecommerce-network

 redis-container:
  image: redis:latest
  ports:
   - "6379:6379"
  volumes:
   - ../redis-cache:/data

 rabbitmq-container:
  image: rabbitmq:4.1.2-management
  ports:
   - "5672:5672"
   - "15672:15672"
  environment:
   - RABBITMQ_DEFAULT_USER=user
   - RABBITMQ_DEFAULT_PASS=password
  networks:
   - ecommerce-network

 products-microservice:
  image: rbcadaing/ecommerce-products-microservice:latest
  build:
      context: ../
      dockerfile: eCommerceSolution.ProductsService/ProductsMicroService.API/Dockerfile
  environment:
   - ConnectionStrings__DefaultConnection=Server=mysql-container;Port=3306;Database=ecommerceproductsdatabase;Uid=root;Pwd=mysqlpw;
   - RabbitMQ__HostName=rabbitmq-container
   - RabbitMQ__UserName=user
   - RabbitMQ__Password=password
   - RabbitMQ__Port=5672
   - RabbitMQ__Product_Exchange=product.exchange
  depends_on:
      - mysql-container
  ports:
   - "8080:8080"
  networks:
   - ecommerce-network

 users-microservice:
  image: rbcadaing/ecommerce-users-microservice:latest
  build:
      context: ../
      dockerfile: eCommerceSolution.UserService/eCommerce.API/Dockerfile
  environment:
   - ConnectionStrings__PostgresConnection=Host=postgres-container:5432;Database=eCommerceUsers;User Id=postgres;Password=postgrespw;
  depends_on:
      - postgres-container
  ports:
   - "9090:9090"
  networks:
   - ecommerce-network

 orders-microservice:
  image: rbcadaing/ecommerce-orders-microservice:latest
  build:
      context: ../
      dockerfile: eCommerceSolution.OrdersMicroservice/OrdersMicroservice.API/Dockerfile
  environment:
   - ConnectionStrings__MongoDB=mongodb://root:mongopw@mongodb-container
   - UsersMicroserviceUrl=http://users-microservice:9090
   - ProductsMicroserviceUrl=http://products-microservice:8080
   - OrdersDatabaseName=OrdersDatabase
   - ConnectionStrings__Redis=redis-container:6379
   - RabbitMQ__HostName=rabbitmq-container
   - RabbitMQ__UserName=user
   - RabbitMQ__Password=password
   - RabbitMQ__Port=5672
   - RabbitMQ__Product_Exchange=product.exchange
  depends_on:
      - mongodb-container
  ports:
   - "9091:8080"
  networks:
   - ecommerce-network

 apigateway-microservice:
  image: apigateway
  build:
   context: ../
   dockerfile: eCommerceSolution.GatewayMicroservice/ApiGateway/Dockerfile
  ports:
   - "4000:8080"
  networks:
   - ecommerce-network


networks:
 ecommerce-network:
  driver: bridge
