name: Docker Image Build MongoDB

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ./deployment
      run: |
        ls
        docker build . --file mongodb/Dockerfile --tag my-image-name:$(date +%s)
